version: '3.9'

services:
  server:
    container_name: auth-system-server
    env_file: .env
    build: 
      context: .
      dockerfile: ./Dockerfile
      target: dev
      tags:
        - "amirmuha/auth-system-dev"
    ports: 
      - "4220:${PORT}"
      - "4225:${MICROSERVICE_PORT}"
    volumes:
      - ./:/usr/app/
    depends_on:
      - postgres
      - redis
    networks: 
      - auth-system

  redis: 
    image: redis
    ports: 
      - "6380:6379"
    networks: 
      - auth-system

  postgres:
    container_name: auth-system-postgres
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/
    networks: 
      - auth-system

networks: 
  auth-system:
    name: auth-system
volumes:
  postgres:
    name: auth-system-postgres

